### ISSUE TITLE
/about

### ISSUE THREAD

**Issue by spNullReferenceException** [SeniorProjectNRE/CSL-Website-Redesign#10]
•	Breadcrumbs should be About Us with no link
•	In 2nd bullet under What We Do, nonpartisan should have no hyphen. 
•	We’re not liking the zebra pattern for paragraphs.
•	In 2nd bullet under What We Do, please remove hyphen from nonpartisan. 
•	In the last sentence at bottom of page, let’s imbed a cslinfo@library.ca.gov link in the word “email”: Please send us an email and let us know how we can make it easier for you to get what you need.

**Comment by alan-cleetus** [comment]
breadcrumb fixed.
hyphen removed.
removed zebra pattern.
embedded email
