### ISSUE TITLE
/art

### ISSUE THREAD

**Issue by spNullReferenceException** [SeniorProjectNRE/CSL-Website-Redesign#12]
•	Very hard to see the descriptions for the images.
•	Please replace the first two sentences with the following:  The California State Library can provide reproductions of images in its collections to California State Legislators. Below is a sampling of different items within the collections of the State Library that can be duplicated at your request.

**Comment by alan-cleetus** [comment]
had to use fancybox 3 to make good looking galleries.
fixed text
