### ISSUE TITLE
/services/apply

### ISSUE THREAD

**Issue by spNullReferenceException** [SeniorProjectNRE/CSL-Website-Redesign#18]
•	Remove My work and home information are the same
•	Only show I am…. Drop down on load, other fields will show after they select.  Will get a cannot apply message if they choose general public
•	After the first check box, please add the following:
Sign up for California State Library newsletters, and news and alerts on upcoming events:
__ State Library news and events.
__ Quarterly information for patrons of the Braille and Talking Book Library.
__ Lunch with a Side of Research runs Mondays with a listing of free policy/research lunch events.
__ Studies in the News runs Wednesdays, providing recent studies that may be useful to policy discussions.
•	Breadcrumbs?

**Comment by alan-cleetus** [comment]
removed checkbox.
added breadcumbs.
added 4 extra checkboxes at the end.
added js to mimic what the client wants.
